name: artifacts poc 1

on:
  repository_dispatch:
    types: [makeartifacts]

jobs:
  make-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        run: |
          echo "something"
