
name: workflow get changed folder on push action

on:
  push:
    branches:
      - main
    paths:
      - 'Services/**'

jobs:
  change_folder:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: get changed folder
        uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          foldersOnly: true
          format: json

      - name: echo
        run: echo ${{ steps.get_changed.outputs.changed }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
          echo ${{ toJson(steps.changed-files.outputs) }} 

      - name: If something changed in test-service-3 folder
        id: changed-files-test-service3
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Services/test-service3

      - name: If something changed in test-service-4 folder
        id: changed-files-test-service4
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Services/test service4

      - name: Run if changed in service 4
        if: steps.changed-files-test-service4.outputs.any_changed
        run: |
          echo "changed in service 4"

      - name: Run if changed in service 3
        if: steps.changed-files-test-service3.outputs.any_changed
        run: |
          echo "changed in service 3"