
name: workflow get changed folder on push action

on:
  push:
    branches:
      - main
    paths:
      - 'Services/**'

jobs:

  change_folder:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get changed folder
        uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          foldersOnly: true
          format: json

      - name: echo
        run: echo ${{ steps.get_changed.outputs.changed }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: 'true'

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
      - name: If something changed in test-service-3 folder
        id: changed-files-test-service3
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: 'true'
          files: |
            Services/test-service3

      - name: If something changed in test-service-4 folder
        id: changed-files-test-service4
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: 'true'
          files: |
            Services/test\ service4

      - name: If something changed in test-service-1 folder
        id: changed-files-test-service1
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: 'true'
          files: |
            Services/test-service1
            

      - name: If something changed in test-service-2 folder
        id: changed-files-test-service2
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: 'true'
          files: |
            Services/test-service2

      - name: Run if changed in service 4
        if: steps.changed-files-test-service4.outputs.any_changed == 'true'
        run: |
          echo "changed in service 4"

      - name: Run if changed in service 3
        if: steps.changed-files-test-service3.outputs.any_changed == 'true'
        run: |
          echo "changed in service 3"

      - name: Run if changed in service 2
        if: steps.changed-files-test-service2.outputs.any_changed == 'true'
        run: |
          echo "changed in service 2"

      - name: Run if changed in service 1
        if: steps.changed-files-test-service1.outputs.any_changed == 'true'
        run: |
          echo "changed in service 1"

    outputs:
      isFolder3Changed: ${{ steps.changed-files-test-service3.outputs.any_changed }}
      isFolder4Changed: ${{ steps.changed-files-test-service4.outputs.any_changed }}
      isFolder2Changed: ${{ steps.changed-files-test-service2.outputs.any_changed }}
      isFolder1Changed: ${{ steps.changed-files-test-service1.outputs.any_changed }}

  run-action:
    needs: change_folder
    runs-on: ubuntu-latest
    steps:

      - name: echo variables
        run: |
          echo "${{needs.change_folder.outputs.isFolder3Changed}}"
          echo "${{needs.change_folder.outputs.isFolder4Changed}}"

      - name: Run action if changed in service 4
        if: needs.change_folder.outputs.isFolder3Changed == 'true'
        run: |
          echo "changed in service 4"

      - name: Run action if changed in service 3
        if: needs.change_folder.outputs.isFolder4Changed == 'true'
        run: |
          echo "changed in service 3"

      - name: Run action if changed in service 2
        if: needs.change_folder.outputs.isFolder2Changed == 'true'
        run: |
          echo "changed in service 2"

      - name: Run action if changed in service 1
        if: needs.change_folder.outputs.isFolder1Changed == 'true'
        run: |
          echo "changed in service 1"