name: workflow to build the backend artifacts
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - name: echo event
        run: 'echo "payload: ${{ toJson(github.event) }}"'
        
      - name: create file
        run: 'touch somefile.txt'

      - name: append data
        run: 'echo "test" > somefile.txt'

      - name: see data
        run: cat somefile.txt

      - name: save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: somefile.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:

      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: list artifacts
        run: ls -a
       
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: somefile.txt

      - name: see data
        run: cat somefile.txt     
