
name: workflow to build the backend artifacts

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - name: echo event
        run: 'echo "payload: ${{ toJson(github.event) }}"'

      - name: create folder
        run: |
          mkdir testfolder
          mkdir testfolder/insidefolder
          touch testfolder/insidefolder/somefileinside.txt


      - name: create file
        run: |
          touch testfolder/somefile1.txt
          touch testfolder/somefile2.txt

      - name: append data
        run: |
          echo "test1" > testfolder/somefile1.txt
          echo "test2" > testfolder/somefile2.txt

      - name: see data
        run: cat testfolder/somefile1.txt

      - name: save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./testfolder

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:

      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: list artifacts
        run: ls -aR
       
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: see data
        run: cat my-artifact/somefile2.txt     


      - name: list current directory
        run: pwd     