
name: simple shell actions workflow

on:
  push:
  repository_dispatch:
    types: [shellaction]


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: simple shell command
        run: |
          docker image ls

      - name: simple shell command
        run: |
          echo "hello world"
          echo "github sha: ${GITHUB_SHA}"
          echo "github sha short: ${GITHUB_SHA:0:8}"

      - name: multiple shell command
        run: |
          node -v
          npm -v
      - name: python command
        id: pythoncommand
        shell: python
        run: |
          import platform
          print(platform.processor())

      - name: print step output
        run: |
          echo ${{ toJson(steps.pythoncommand.outputs) }}

  test-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: simple shell command
        run: |
          docker image ls
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_SHA_SHORT: ${GITHUB_SHA:0:8}"
          docker tag product-service:latest "${ECR_REGISTRY}/${PRODUCT_SERVICE_ECR_REPO_NAME}"
