
name: simple shell actions workflow

on:
  push:
  repository_dispatch:
    types: [shellaction]


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: simple shell command
        run: |
          echo "hello world"
          echo "github sha: ${github.sha}"

      - name: multiple shell command
        run: |
          node -v
          npm -v
      - name: python command
        id: pythoncommand
        shell: python
        run: |
          import platform
          print(platform.processor())
          print(platform.processor())

      - name: print step output
        run: |
          echo ${{ toJson(steps.pythoncommand) }}